### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by KotlinFactory** [Minecrell/plugin-yml#13]
The version found at plugins.gradle.org is still 0.4.0. It does not contain support for libraries.
I would love to make use of this feature without having to add the plugin manually to the classpath.

**Comment by stephan-gh** [comment]
Sorry for the delay. 0.5.0 is available on plugins.gradle.org now!

- https://plugins.gradle.org/plugin/net.minecrell.plugin-yml.bukkit/0.5.0
- https://plugins.gradle.org/plugin/net.minecrell.plugin-yml.bungee/0.5.0
