### ISSUE TITLE
'permissions' cannot be applied to '(groovy.lang.Closure)' with Bukkit Groovy

### ISSUE THREAD

**Issue by AerWyn81** [Minecrell/plugin-yml#14]
Hi, using the plugin at the 0.5.0 version with Bukkit Groovy, running into this issue when adding permissions : 
![](https://i.imgur.com/ca1WeEl.png)

![](https://i.imgur.com/yJIx1w5.png)
![](https://i.imgur.com/oo168KR.png)

**Comment by stephan-gh** [comment]
Is there also an error at runtime or just in the IDE? IDE support is generally quite bad for Groovy, use Kotlin DSL if you want proper IDE support.

**Comment by AerWyn81** [comment]
Oh yes, I forgot to specify that. The warning seems to be only on the IDE side, the file is generated fine. So it's an interpretation issue between Gradle & the IDE? Seriously.. Haha

If I use Kotlin DSL, I need to have a Kotlin plugin and not a Java one or is it independent?

**Comment by stephan-gh** [comment]
The language you use for the Gradle build script is independent of what you build with it. You can have a kotlin-dsl Gradle build script that builds a Java-only project.

**Comment by AerWyn81** [comment]
Ok great, thanks for the info!
