### ISSUE TITLE
Support Shadow Plugin

### ISSUE THREAD

**Issue by toddharrison** [Minecrell/plugin-yml#17]
When trying to use the plugin-yml in combination with com.github.johnrengelman.shadow (often used to shadow dependencies into the jar) library dependencies are shadowed into the jar.

Library dependencies should be compileOnly in this context.

**Comment by stephan-gh** [comment]
If you're producing a shadow JAR (with dependencies included), why do you want to use the library dependency mechanism?

**Comment by toddharrison** [comment]
Some libs are not available through maven central repo. Specifically, those libs would need to be shadowed. My specific example, I want to have the kotlin libs as libraries (they are large and I use them in multiple plugins) but must shadow in a dependency lib not in maven central (xyz.jpenilla:reflection-remapper) that cannot be used directly as a plugin itself.

Right now, I do this manually, but would like to use your plugin and not have to processResources to get build variables into plugin.yml.

**Comment by stephan-gh** [comment]
This seems to work fine for me?

```kotlin
import net.minecrell.pluginyml.bukkit.BukkitPluginDescription

plugins {
    java
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("net.minecrell.plugin-yml.bukkit") version "0.5.1"
}

version = "1.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.ocpsoft.prettytime:prettytime:4.0.6.Final")
    library("net.kyori:adventure-api:4.9.3")
}

bukkit {
    main = "com.example.testplugin.TestPlugin"
    apiVersion = "1.13"
}
```

```
$ gradle clean build shadowJar
```

The -all.jar contains only prettytime, not the adventure-api:

![Screenshot_20220103_212020](https://user-images.githubusercontent.com/3035868/147976353-0232d4ff-deec-4928-8f50-889493678774.png)

The generated `plugin.yml`:

```yaml
name: pluginymltest2
version: 1.0
main: com.example.testplugin.TestPlugin
libraries:
 - net.kyori:adventure-api:4.9.3
api-version: 1.13
```

**Comment by toddharrison** [comment]
When I tried that I was getting the library included in the shadowed jar. When I run I was having class conflicts because it was in two places. Review the shadow jar created and see if it is the same for you. I will review on this side as well.

Edit: Sorry, missread what you wrote there. I will try it out again on my side. It didn't seem to be working for me but it is for you. Thanks!

**Comment by toddharrison** [comment]
Ok, made this one change to use kotlin instead of java:

```kotlin
import net.minecrell.pluginyml.bukkit.BukkitPluginDescription

plugins {
    kotlin("jvm") version "1.6.10"
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("net.minecrell.plugin-yml.bukkit") version "0.5.1"
}

version = "1.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.ocpsoft.prettytime:prettytime:4.0.6.Final")
    library("net.kyori:adventure-api:4.9.3")
}

bukkit {
    main = "com.example.testplugin.TestPlugin"
    apiVersion = "1.13"
}
```

That results in including all the kotlin standard dependencies in the shadow jar:

<img width="606" alt="Screen Shot 2022-01-05 at 7 39 51 PM" src="https://user-images.githubusercontent.com/1626862/148319726-df735a51-b838-4f97-977f-f5d78ddfb1a5.png">

You can see the size of the all jar. I'm not sure why adding the plugin would result in the shadow jar including the source. I have also tried adding it to the dependencies explicitly:

```kotlin
dependencies {
    implementation("org.ocpsoft.prettytime:prettytime:4.0.6.Final")
    library(kotlin("stdlib"))
    // library("org.jetbrains.kotlin:kotlin-stdlib:1.6.10")
    library("net.kyori:adventure-api:4.9.3")
}
```

But neither of those seemed to make any difference. It looks like it's the fault of the kotlin plugin to me, but I'm not sure why.

This works correctly if I use the kotlin plugin and manually make the shadow jar and the plugin.yml:

```kotlin
plugins {
    kotlin("jvm") version "1.6.10"
//    id("net.minecrell.plugin-yml.bukkit") version "0.5.1" // Generates plugin.yml
    id("com.github.johnrengelman.shadow") version "7.1.2" // shadowJar
}

repositories {
    mavenCentral()
}

dependencies {
    paperDevBundle("1.18.1-R0.1-SNAPSHOT")
    compileOnly(kotlin("stdlib"))
}
```

```yaml

name: ${project.name}
version: ${project.version}
...
api-version: 1.18

...

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10
```

**Comment by stephan-gh** [comment]
Sorry, somehow I forgot to reply to this again. Are you still having problems with this?

It looks like the Kotlin Gradle plugin automatically adds a compile dependency on kotlin-stdlib if you do not add it explicitly to another dependency configuration. The problem is, that those configurations are fixed in the Kotlin Gradle plugin...

https://github.com/JetBrains/kotlin/blob/7d56ef19255df61f8c63382521a1a512dfb3956a/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/sources/KotlinDependencyScope.kt#L30-L38

... and obviously the new `library` configuration from plugin-yml is not part of it.

This is documented here: https://kotlinlang.org/docs/gradle.html#dependency-on-the-standard-library  
It also describes a way to disable this behavior if it does not work as expected (like in your case). So, I would recommend that you add `kotlin.stdlib.default.dependency=false` to your project `gradle.properties` and then try again.

Hope that helps and sorry again for the late reply!

**Comment by toddharrison** [comment]
Thanks for that info! I will give it a try and let you know shortly.

**Comment by toddharrison** [comment]
I was able to get this working after making all the kotlin dependencies a separate plugin. Apparently there are issues with sharing the same libraries between plugins that also depend on each other. I will close this issue. Thanks for all the assistance and I have it working correctly with generating the plugin file now.
