### ISSUE TITLE
A problem was found with the configuration of task ':generateBukkitPluginDescription' (type 'GeneratePluginDescription').   - In plugin 'net.minecrell.plugin-yml.bukkit' type 'net.minecrell.pluginyml.GeneratePluginDescription' property 'pluginDescription.main' doesn't have a configured value.

### ISSUE THREAD

**Issue by deestt** [Minecrell/plugin-yml#25]

**Comment by deestt** [comment]
im using subprojects

**Comment by robalmeister** [comment]
if (!project.name.contains("velocity")){
        bukkit {
            main = "pl.pvpchmura." + project.name.split("-")[1] + (project.name.split("-").length == 4 ? project.name.split("-")[3] : "")+ ".BukkitPlugin"
            version = project.version
            name = project.name
        }
    }
