### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by alex6777** [Minecrell/plugin-yml#35]
please ❤️

**Comment by stephan-gh** [comment]
If you're interested in the new Paper plugin feature, are you sure you want the release before #34 is merged? :D

**Comment by alex6777** [comment]
Never know how long that could take 😟 and it's still supported until 1.21. Plenty of time for another release later

**Comment by alex6777** [comment]
bump, and can merge #34 at the same time

**Comment by stephan-gh** [comment]
It is done.
