### ISSUE TITLE
Commands (and very likely permissions) are broken on Gradle 4.10

### ISSUE THREAD

**Issue by mikroskeem** [Minecrell/plugin-yml#4]
When I try to create a new command, then Gradle throws an exception and mentions something about "Command with name 'creategame' not found.". Here's the stacktrace: https://paste.wut.ee/avecocenoz.cs  
I guess that something changed in Gradle API? :thinking:  
It works in 4.8 perfectly. I tried both 0.2.1 and 0.3.0 plugin versions.

I have this in my `build.gradle.kts`:

```kotlin
bukkit {
    name = "x"
    description = "y"
    authors = listOf("mikroskeem")
    main = "z"

    commands {
        "creategame" {
            description = "Creates a new game"
        }
    }
}
```

Current workaround is to use this:
```kotlin
bukkit {
    // ...
    commands.create("creategame") {
        description = "Creates a new game"
    }
}
```

**Comment by stephan-gh** [comment]
See https://github.com/gradle/kotlin-dsl/releases/tag/v1.0-RC6 "Container `String` invoke now is `named()` instead of `maybeCreate()`" or https://github.com/gradle/kotlin-dsl/issues/907.

You should use `register` instead now, as that will be initialized lazily:

```kts
commands {
    register("creategame") {
        // ...
    }
}
```

**Comment by stephan-gh** [comment]
I'll keep this open as a reminder to update the README.
