### ISSUE TITLE
Repository change required on readme.md

### ISSUE THREAD

**Issue by LINCKODE** [Minecrell/plugin-yml#47]
The README.md specifies the maven repository as "https://papermc.io/repo/repository/maven-public/"
The plugin is actually available at "https://plugins.gradle.org/m2/"

**Comment by stephan-gh** [comment]
Do you mean in the Paper examples? The repository for plugin-yml doesn't have to be specified manually if you use the `plugins { ... }` block.

The papermc repository was probably meant for the PaperAPI dependency, although it's a bit inconsistent that it's specified in the Paper example but not for Bukkit etc.

**Comment by LINCKODE** [comment]
Yeah, I was talking about the Paper examples. I'm sorry about the first message, I understand now that the repo in the example was for something else. I am actually doing some maintenance on some Gradle code that uses the legacy way of specifying plugins, so in this case I was looking for a repository to declare.
I think that specifying where the plugin is hosted might be useful for some people so if you could mention it somewhere on the README I'd be thankful.

**Comment by stephan-gh** [comment]
I think that legacy way of specifying plugins has been largely obsolete for quite some time, so I would prefer not documenting it anymore.

Most Gradle plugins are uploaded to the Gradle plugin portal nowadays (since this is what the `plugins { ... }` block most easily works with). In that case you should be able to use

```gradle
buildscript {
    repositories {
        gradlePluginPortal()
    }
}
```

without giving an explicit URL.

**Comment by LINCKODE** [comment]
What you're saying sounds reasonable, thanks for your time! I'm sorry for bothering you with this pointless issue, next time I'll try to pay more attentions to details. Cheers!
